### ISSUE TITLE
Can't get it to run :(

### ISSUE THREAD

**Issue by joechrz** [congalong/connect4#1]
Hey—

We're trying to get this solution running but can't seem to.  The instructions in the README aren't quite working:

 * the `package.json` needed a module name change to remove the space (was preventing `npm install` from working)
 * `Uncaught Error: Cannot find module "./app/index.js"` - our best guess is because of a missing babel config

Mind taking a look and getting back to us?

(PS: we love the extra effort!)

**Comment by joechrz** [comment]
Nevermind, hosted version works just fine :)

**Comment by congalong** [comment]
I may have been overzealous in stripping out some super secret stuff :( Glad the hosted one works!
